config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  put '/tweets/:id/like', to: 'tweets#like', as: 'like_tweet'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tweets#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :author, length: { minimum: 4 }

    validates :content, length: { minimum: 4}
    validates :content, length: { maximum: 280}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :error

rescue_from ActionController::InvalidAuthenticityToken, with: :redirect_to_referer_or_path

  def redirect_to_referer_or_path
    flash[:error] = "La cache se ha borrado junto al AuthenticityToken, refresca la pagina"
    redirect_to tweets_url
  end
  
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy, :like]
  add_flash_types :success, :error
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all.order(created_at: :desc)
    @newTweet= Tweet.new
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.likes = 0
    respond_to do |format|
      if @tweet.save
        unless session[:created_ids].nil?
          session[:created_ids] = session[:created_ids] << @tweet.id
        else
          session[:created_ids] = [@tweet.id]
        end

        format.html { redirect_to tweets_url, success: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        errors = []
        @tweet.errors.each do |error|
          errors << error.full_message 
        end
        format.html { redirect_to tweets_url, error: errors }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, success: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def like
    @tweet.likes = @tweet.likes + 1
    @tweet.save

    respond_to do |format|
      format.html { redirect_to tweets_url, success: 'Like <3 !' } 
      format.json { head :ok } 
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy

    respond_to do |format|
      if session[:created_ids].nil? || session[:created_ids].exclude?(@tweet.id)
          format.html { redirect_to tweets_url, error: 'You are not allowed to delete this tweet.' }
          format.json { head :forbidden }   
      else 
        @tweet.destroy
        session[:created_ids].delete(@tweet.id)
        format.html { redirect_to tweets_url, success: 'Tweet was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:author, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/application/hello.html.erb
<p>hola</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waslab05</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
<div class="contenedor-formulario">
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="display: flex;">
    <%= form.label :author, "Your name:", style:"font-size:13px; margin-right:5px;" %>
    <%= form.text_field :author, size: '70' %>
  </div>

  <div class="field" style="display: flex;">
    <div style="display: flex; padding-right:4em;">
      <%= form.label :content, "Your tweet:", style:"align-self:center;font-size:13px; margin-right:5px;" %>
      <%= form.text_area :content, size:'70' %>
    </div>

    <div class="actions" style="align-self: end;">
      <%= form.submit "Tweet!"%>
    </div>

  </div>



</div>


<% end %>

app/views/tweets/_list.html.erb
<%
    date = Time.now.strftime("%A, %B %d, %Y") 
    date_writed = false
  %>
  <div class="tweets-container">
    <% @tweets.each do |tweet|%>

    <% if date != tweet.created_at.strftime("%A, %B %d, %Y") %>
      <%
        date = tweet.created_at.strftime("%A, %B %d, %Y") 
        date_writed = false
      %>      
    <% end %>

    <% if !date_writed %>
      <h3>... <%= date%></h3>
      <%date_writed = true%>
    <% end %>
      <div class="tweet">
        <div class="tweet-like">
          <span class="numlikes"><%= tweet.likes%></span>
          <br>
          <span class="smallfont">
            people like this
            <span>
              <br>
              <h3>
                <%= link_to 'Like', like_tweet_path(tweet.id), method: :put %>
              </h3>
            </span>
          </span>
        </div>

        <div class="tweet-content">

          <h4>
            <em><%= "#{tweet.author}"%></em>
            @ <%= tweet.created_at.strftime("%H:%M")%>
          </h4>

          <p><%= tweet.content %></p>
          <p style="text-align:right;">
            <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
          </p>
        
        </div>

      </div>
    <%end%>
  </div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div>
  <div>
    <h1 style="text-align:center; color: #660000">Wall of Tweets - RoR Edition 2021</h1>
  </div>

  <%= render 'form', tweet: @newTweet%>

  <% flash.each do |key, value| %>
    <div class="wotitem">
      <span class="<%= key %>">
        <% if value.is_a? Array %>
          <% value.each_with_index do |error, index| %>
            <%= error %> 
            <% if index != value.count-1 %> 
              <%= " and " %>
            <%end%>
          <% end %>
        <% else %>
          <%= value %>
        <% end %>
      </span>
    </div>
  <% end %>


  <%= render 'list', tweets: @tweets%>
  
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @tweet.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>